name: notification
on:
    workflow_dispatch:
    pull_request_target:
        types:
            - closed
        branches:
            - main
        paths:
            - "include/**"
            - "languages/**"
            - "layout/**"
            - "scripts/**"
            - "source/**"
            - "package.json"
jobs:
    notify:
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) }}
        runs-on: ubuntu-latest
        environment: ABYSSERS_NOTIFY_ENV
        steps:
            - name: "[Notify Users' Repo]"
              run: |
                  curl \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \ 
                    -H "Authorization: token ${{ secrets.MORILENCE_GENERAL_PAT }}" \
                    https://api.github.com/repos/Abyssers/blog/dispatches \
                    -d '{ "event_type": "theme-updated", "client_payload": { "changes": ${{ github.event.changes }} } }'
