name: notification
on:
    pull_request_target:
        types:
            - closed
        branches:
            - main
        paths:
            - "include/**"
            - "languages/**"
            - "layout/**"
            - "scripts/**"
            - "source/**"
            - "package.json"
jobs:
    notify:
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_target' && github.event.pull_request.merged == true) }}
        runs-on: ubuntu-latest
        environment: ABYSSERS_NOTIFY_ENV
        steps:
            - name: "[Notify Users of Theme Updates]"
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.MORILENCE_GENERAL_PAT }}
                  repository: Abyssers/blog
                  event-type: theme-updated
                  client-payload: '{ "changes": "${{ github.event.changes }}" }'
